### ISSUE TITLE
Struggling to detect interrupt

### ISSUE THREAD

**Issue by cefn** [Megunolink/WakeOnSerial#1]
I've been experimenting with the WakeOnSerial sketch, and found that it doesn't appear to run the WakeHandler function at all. I must be somehow confused how this works.

I've added very few lines for debugging, and these changes should be easy to replicate (and perhaps easier to follow if these lines are copy-pasted). I'm using the latest LowPower.h and PinChangeInt.h from https://github.com/rocketscream/Low-Power and  https://github.com/GreyGnome/PinChangeInt

I declared a global bool variable to detect if there was an interrupt...

```
volatile bool sleepDisturbed;
```

I added the following line to WakeHandler...

```
  sleepDisturbed = true;
```

This line is called before entering powerdown...

```
sleepDisturbed = false; 
```

And I report the result after waking as follows...

```
    if(!sleepDisturbed){
      Serial.println("Yawn. I'm awake!");      
    }    
    else{
      Serial.println("Who woke me up?");
    }
```

What I find is that even when the LowPower.powerDown call terminates early because the interrupt was triggered by a serial event, it never seems to call the WakeHandler function, never sets sleepDisturbed to true, and hence, never responds "Who woke me up?". 

Any idea what's wrong with the PCintPort::attachInterrupt setup which means that the WakeHandler function isn't called? Is there a fix?

**Comment by Megunolink** [comment]
Hi Cefn, what hardware are you working with? We originally wrote this to work on a project using a ATmega644 so its possible there are differences. If you let us know we can try to replicate it at this end.

Cheers
Phil

**Comment by cefn** [comment]
Thanks, Megunolink

I'm targeting the ATMEGA328 (with an Arduino Uno bootloader) but I'd be curious to know if the function runs at all even on your preferred target platform. Is it easy to verify with the four chunks of code I've provided?

**Comment by cefn** [comment]
Sorry, for power-oriented projects I should clarify the full model 328P-PU

**Comment by PaulMartinsen** [comment]
It looks like the pin-change interrupt vector isn't executing when waking the device with the serial port. It still wakes the device; just the interrupt vector doesn't run. This is also the case if I call Serial.end() to disable the serial port before putting the device to sleep. It does work if you attach the pin-change interrupt to one of the other pins (say 7) by modifying SERIAL_RX_PIN. I also tried without the PCintPort library (see 2015-04-RawInterrupts branch), but that doesn't work either. 

I believe it does work on the 644p chip, where the code was originally developed, because I had a periodic wake source as well as the serial input and keep the micro awake if the serial port was the wake source but I can't easily test that right now unfortunately. 

There may be some interaction with the sleep mode as well. If I replace the LowPower.powerDown call with: 
    //LowPower.powerDown(SLEEP_8S, ADC_OFF, BOD_OFF);  
    g_bSerialWoke = false; 
    while (!g_bSerialWoke)
      ;
then it blocks until g_bSerialWork is set in the WakeHandler. Note, g_bSerialWake should be declared as volatile for this to work. 

At this point, I've run out of ideas! Would be very interested if you find a solution.

**Comment by cefn** [comment]
I arrived at the hack of putting a wire between the Serial pin and Pin2 - an External Interrupt Pin (INT0)  which _does_ support a function pointer invocation. 

Before shutting down serial, I set up an interrupt on pin 2, then deliberately trash any Serial buffer contents on wake.

Reference tested code is at...https://github.com/ShrimpingIt/projects/blob/752cf2e03d16c5aa810f726d97b623c8ed6488e1/sketchbook/shrimpingit/alarmclock/Clock02SetAndReportIso/Clock02SetAndReportIso.ino - search for 'sleep' and 'wake' for relevant functions. The sketch is a real time AlarmClock where the time is programmed over Serial so there's a whole load of other code in there. 

The intent is for people to use this sketch to personalise their own Alarm Clocks based on...
http://start.shrimping.it/project/alarmclock/kit.png

An alternative is to use Idle state with all the subsystems manually off except the USART, like...
LowPower.idle(SLEEP_8S, ADC_OFF, TIMER2_OFF, TIMER1_OFF, TIMER0_OFF,
SPI_OFF, USART0_ON, TWI_OFF);
...but it's not as low power as powerDown so I was keen to get powerDown to work properly especially for a clock which might need to run for years off a few AAAs.

For reference seems that LOW is specifically not supported except for External Interrupt Pins INT0 and INT1 as described at https://github.com/GreyGnome/EnableInterrupt/wiki/Usage#Arduino_UnoDuemilanoveetc
"For Pin Change Interrupt pins, the modes supported are RISING, FALLING, or CHANGE. For External Interrupt pins, the modes supported are the same, plus LOW."

I did wonder if certain types of event _are_ able to trigger function calls on pin 0, (not LOW, which is for External pins only), but I haven't figured out how, yet, and the wire hack is good enough for me.
